version: "3.8"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  thehive:
    image: strangebee/thehive:5
    container_name: thehive
    depends_on:
      - elasticsearch
    environment:
      - STORAGE=elasticsearch
      - INDEX=thehive
      - ES_HOST=http://elasticsearch:9200
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - thehive-data:/etc/thehive
    ports:
      - "9000:9000"

  cortex:
    image: thehiveproject/cortex:3.1
    container_name: cortex
    depends_on:
      - elasticsearch
    environment:
      - JOB_DIRECTORY=/opt/cortex/jobs
    volumes:
      - cortex-data:/etc/cortex
      - cortex-jobs:/opt/cortex/jobs
    ports:
      - "9001:9001"

  mail:
    image: ixdotai/smtp
    environment:
      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
      - "SMARTHOST_USER=${SMARTHOST_USER}"
      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"

  redis:
    image: valkey/valkey:7.2
    command: "--requirepass '${REDIS_PASSWORD:-redispassword}'"
    healthcheck:
      test: "valkey-cli -a '${REDIS_PASSWORD:-redispassword}' -p ${REDIS_PORT:-6379} ping | grep -q PONG || exit 1"
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s
      start_interval: 5s

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
    command: >
      --innodb-buffer-pool-size=${INNODB_BUFFER_POOL_SIZE:-2048M}
      --innodb-change-buffering=${INNODB_CHANGE_BUFFERING:-none}
      --innodb-io-capacity=${INNODB_IO_CAPACITY:-1000}
      --innodb-io-capacity-max=${INNODB_IO_CAPACITY_MAX:-2000}
      --innodb-log-file-size=${INNODB_LOG_FILE_SIZE:-600M}
      --innodb-read-io-threads=${INNODB_READ_IO_THREADS:-16}
      --innodb-stats-persistent=${INNODB_STATS_PERSISTENT:-ON}
      --innodb-write-io-threads=${INNODB_WRITE_IO_THREADS:-4}
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD status
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 5s

  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    build:
      context: core/.
      args:
        - CORE_TAG=${CORE_TAG}
        - CORE_COMMIT=${CORE_COMMIT}
        - CORE_FLAVOR=${CORE_FLAVOR:-full}
        - PHP_VER=${PHP_VER}
        - PYPI_REDIS_VERSION=${PYPI_REDIS_VERSION}
        - PYPI_LIEF_VERSION=${PYPI_LIEF_VERSION}
        - PYPI_PYDEEP2_VERSION=${PYPI_PYDEEP2_VERSION}
        - PYPI_PYTHON_MAGIC_VERSION=${PYPI_PYTHON_MAGIC_VERSION}
        - PYPI_MISP_LIB_STIX2_VERSION=${PYPI_MISP_LIB_STIX2_VERSION}
        - PYPI_MAEC_VERSION=${PYPI_MAEC_VERSION}
        - PYPI_MIXBOX_VERSION=${PYPI_MIXBOX_VERSION}
        - PYPI_CYBOX_VERSION=${PYPI_CYBOX_VERSION}
        - PYPI_PYMISP_VERSION=${PYPI_PYMISP_VERSION}
        - PYPI_MISP_STIX_VERSION=${PYPI_MISP_STIX_VERSION}
        - PYPI_SETUPTOOLS=${PYPI_SETUPTOOLS}
        - PYPI_SUPERVISOR=${PYPI_SUPERVISOR}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/:/var/www/MISP/app/Config/
      - ./logs/:/var/www/MISP/app/tmp/logs/
      - ./files/:/var/www/MISP/app/files/
      - ./ssl/:/etc/nginx/certs/
      - ./gnupg/:/var/www/MISP/.gnupg/
    environment:
      - BASE_URL=${BASE_URL}
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispassword}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}
      # Add your additional required environment variables here

volumes:
  esdata:
  thehive-data:
  cortex-data:
  cortex-jobs:
  mysql_data:
